name: Build

on: [push, pull_request]

jobs:
  desktop:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest }
        - { name: Windows, os: windows-2025 }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@main
      with:
        version: sdl3-head
    - name: Get project sources
      uses: actions/checkout@v4
    - name: Configure (CMake)
      run: cmake -B build ${{ matrix.platform.flags }} -DDOWNLOAD_DEPENDENCIES=OFF
    - name: Build (CMake)
      run: cmake --build build/

  emscripten:
    name: Emscripten
    runs-on: ubuntu-latest
    steps:
      - name: Get project sources
        uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@master
      - name: Configure (CMake)
        run: emcmake cmake -B build ${{ matrix.platform.flags }} -DDOWNLOAD_DEPENDENCIES=ON
      - name: Build (CMake)
        run: cmake --build build/

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Get project sources
        uses: actions/checkout@v4
      - name: Download SDL3 Android Archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh -R libsdl-org/SDL release download release-3.2.16 -p 'SDL3-devel-*-android.zip'
          unzip "SDL3-devel-3.2.16-android.zip" -d android-project/app/libs SDL3-3.2.16.aar
      - name: Setup required Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build gradle project
        run: |
          cd android-project
          ./gradlew -i assembleRelease
